import {Section} from '@markscript/docx'
import IntroductionChapter from '../chapters/01-introduction.ms'
import FoundationsChapter from '../chapters/02-foundations.ms'
import SystemDesignChapter from '../chapters/03-system-design.ms'
import ImplementationChapter from '../chapters/04-implementation.ms'
import TestingChapter from '../chapters/05-testing.ms'
import Conclusion from '../chapters/conclusion.ms'

<IntroductionChapter />

<FoundationsChapter />

<SystemDesignChapter />

<ImplementationChapter />

<TestingChapter />

<Conclusion />

<Section section="backmatter" />
